version: 0.2
labels:
  buildspec-override: true

phases:
  install:
    runtime-versions:
      java: corretto23
    commands:
      - echo "Installing Maven..."
      - echo "Listing files in CODEBUILD_SRC_DIR..."
      - ls -R $CODEBUILD_SRC_DIR

  pre_build:
    commands:
      - echo "Logging in to Docker hub..."
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo "Building, Testing, and packaging the application..."
      - mvn -f TestingApp/pom.xml clean package -DskipTests || { echo "Maven build failed!"; exit 1; }

  post_build:
    commands:
      - echo "Build completed."
      - echo "Checking for target directory..."
      - find . -type d -name "target"
      - echo "Checking for JAR files..."
      - find . -name "*.jar"

artifacts:
  files:
    - 'TestingApp/target/*.jar'
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
