spring:
  application:
    name: api-gateway

# API Gateway Configuration
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            # Uncomment the following line if you want to redirect
            # - RedirectTo=302, https://www.linkedin.com/in/saiyogesh123/
            
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Sai

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Zipkin Tracing Configuration
management:
  tracing:
    sampling:
      probability: 1.0  # Ensures all requests are traced
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans  # Zipkin server URL
